### ISSUE TITLE
COMO Cliente QUIERO buscar mis películas favoritas PARA no buscarlas por todo el catálogo

### ISSUE THREAD

**Issue by acominf91** [acominf/ViDi#7]

**Comment by DulceMani** [comment]
La busqueda no se implemento ya que no alcanzo el tiempo para hacerlo

**Comment by DulceMani** [comment]
Se dejo la estructura para la implementacion y falto hacer las consultas especiales para cada usuario

**Comment by DulceMani** [comment]
Si el video ya se habia visto y puntuado con una calificacion igual o superior a 4 se agrega en la lista de Favoritos del usuario
